blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/olimorris/onedarkpro.nvim/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/olimorris/onedarkpro.nvim/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: Bug Report
    url: https://github.com/olimorris/onedarkpro.nvim/issues/new?assignees=olimorris&labels=bug&template=bug_report.yaml&title=%5BBug%5D%3A+
    about: If you've already asked for help with a problem and confirmed something is broken with the plugin itself, create a bug report.
